# 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.

In [93]:
import numpy as np
arr = np.array([i for i in range(1,1000) if i % 3 == 0 or i % 5 == 0])
arr.sum()

233168

# 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [139]:
import numpy as np
arr = [1, 2]
while True:
    if arr[-2] + arr[-1] >= 4000000:
        break
    arr.append(arr[-2] + arr[-1])
np.sum([i for i in arr if i % 2 == 0])

4613732

# 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?

In [79]:
num = 600851475143

def prime(num):
    i = 1
    arr = []
    while True:
        if num % i == 0:
            num = num / i
            arr.append(i)
        i = i + 1
        if num < i:
            break
    return arr

prime(num)[-1]

6857

# 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.

In [73]:
import numpy as np

def is_palindromic(num):
    string = str(num)
    for i in range(1,int(len(string)/2) + 1):
        if (string[i-1] != string[-i]):
            return False
    return True

arr = []
for i in range(1000):
    for j in range(1000):
        arr.append(i * j)
data = list(set(arr))

np.array([i for i in data if is_palindromic(i) == True]).max()

906609

# 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [26]:
def lcm(a, b):
    def gcd(a, b):
        while b:
            a, b = b, a % b
        return a
    return a * b // gcd (a, b)
num = 1
for i in range(1,21):
    num = lcm(num,i)
num

232792560

# 6
The sum of the squares of the first ten natural numbers is,
$1^2 + 2^2 + ... + 10^2 = 385$
The square of the sum of the first ten natural numbers is,

$(1 + 2 + ... + 10)^2 = 55^2 = 3025$
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [67]:
import numpy as np
arr = np.arange(1,101)
sum(arr) * sum(arr) - sum(arr*arr)

25164150

# 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10 001st prime number?

In [33]:
i = 3
primes = [2]
while len(primes) <= 10000:
    status = True
    for prime in primes:
        if i % prime == 0:
            status = False
            break
    if status:
        primes.append(i)
    i = i + 2
primes[-1]

104743

# 8

In [25]:
string = '''
73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
'''
line = string.replace("\n","")

def multiply_attr(array):
    cum = 1
    for i in range(len(array)):
        cum = cum * int(array[i])
    return cum

arr = []
for i in range(len(line)):
    arr.append(multiply_attr(list(line[i:i+13])))

import numpy as np
max(np.array(arr))

23514624000

# 9
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

$a^2 + b^2 = c^2$
For example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

$ a^2 + b^2 = c^2 $

$ a^2 + b^2 = {1000-(a+b)}^2 $

$ a^2 + b^2 = {1000-(a+b)}^2 $

$ a^2 + b^2 = 1000^2 - 2 * 1000(a+b) + (a+b)^2$

$0 = 1000^2 -2000(a + b) + 2ab$

In [42]:
for a in range(1, 1001):
    for b in range(1, 1001):
        if 2 * a * b - 2000 * (a + b) + 1000 ** 2 == 0:
            print(a * b * (1000-a-b))

31875000
31875000

# 10
The sum of the primes below 10 is $2 + 3 + 5 + 7 = 17$.
Find the sum of all the primes below two million.

In [38]:
checked_num = set([])
primes = []
for i in range(2,2000000):
    if i in checked_num:
        continue
    primes.append(i)
    j = 1
    while i * j <= 2000000:
        checked_num.add(i * j)
        j = j + 1
sum(primes)

142913828922

# 11
In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [38]:
string = '''08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'''

data = [map(lambda n:int(n),line.split(" ")) for line in string.split("\n")]

max_product = 0
for i in range(0,20):
    for j in range(0,20):
        try:
            yoko = data[i][j] * data[i][j+1] * data[i][j+2] * data[i][j+3]
        except:
            yoko = 0
        try:
            tate = data[i][j] * data[i+1][j] * data[i+2][j] * data[i+3][j]
        except:
            tate = 0
        try:
            naname1 = data[i][j] * data[i+1][j+1] * data[i+2][j+2] * data[i+3][j+3]
        except:
            naname1 = 0
        try:
            naname2 = data[i][j] * data[i+1][j-1] * data[i+2][j-2] * data[i+3][j-3]
        except:
            naname2 = 0
        if max_product < max(yoko,tate,naname1,naname2):
            max_product = max(yoko,tate,naname1,naname2)
print(max_product)

70600674

# 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 
 3: 1,3
 
 6: 1,2,3,6

10: 1,2,5,10

15: 1,3,5,15

21: 1,3,7,21

28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [40]:
import math

$n(n-1)/2$

In [5]:
def func(n):
    return n * (n+1) / 2

$ T_n = \dfrac{n(n-1)}{2} $

$f(T_n) = f(\dfrac{n(n+1)}{2}) = f(\dfrac{n}{2}) * f(n+1) $

In [11]:
f(T_2) = f(1) * f(3)
f(T_3) = f(2) * f(3)
f(T_4) = f(2) * f(5)

SyntaxError: can't assign to function call (<ipython-input-11-4ae8deec9c9d>, line 1)